- name: First practice of conditions concept
  hosts: web
  become: true
  tasks:
  - name: Writing conditions for practice
    #ansible.builtin.command: useradd expense
    ansible.builtin.user:
      name: prasanna
    when: 
      service:
        name: nginx
        enabled: yes
