- name: Install nginx
  hosts: web
  become: true
  tasks:
    - name: installing nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
    - name: starting the niginx server
      service:
        name: nginx
        state: started
    - name: enabling the nginx server
      service:
        name: nginx
        enabled: yes

