- name: Declaring teh variables
  hosts: web
  vars:
    Course: Shell
    Duration: 1hr
  tasks:
    - name: Writing the code
      ansible.builtin.debug:
        msg: "Hi i am learning ansible."
    - name: writing code by declaring variables.
      ansible.builtin.debug:
        msg: "Hi, i am learning {{Course}} in {{Duration}}"